---
# ConfigMap definition
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "overmind-kube-source.fullname" . }}-config
data:
  LOG: {{ .Values.source.log }}
  MAX_PARALLEL: {{ .Values.source.maxParallel | quote }}
  NATS_SERVERS: {{ join "," .Values.source.natsServers }}
  RATE_LIMIT_QPS: {{ .Values.source.rateLimitQPS | quote }}
  RATE_LIMIT_BURST: {{ .Values.source.rateLimitBurst | quote }}
{{- if .Values.source.clusterName }}
  CLUSTER_NAME: {{ .Values.source.clusterName | quote }}
{{- end }}
{{- if .Values.source.apiPath }}
  API_PATH: {{ .Values.source.apiPath | quote }}
{{- end }}
{{- if .Values.source.honeycombApiKey }}
  HONEYCOMB_API_KEY: {{ .Values.source.honeycombApiKey | quote }}
{{- end }}
---
