apiVersion: v1
kind: Secret
metadata:
  name: {{ include "overmind-kube-source.fullname" . }}-secrets
type: Opaque
data:
{{- if .Values.source.apiKey }}
  API_KEY: {{ .Values.source.apiKey | b64enc }}
{{- end }}
