apiVersion: v1
kind: Secret
metadata:
  name: {{ include "overmind-kube-source.fullname" . }}-secrets
type: Opaque
data:
{{- if .Values.source.natsJWT }}
  NATS_JWT: {{ .Values.source.natsJWT | b64enc }}
{{- end }}
{{- if .Values.source.natsNKeySeed }}
  NATS_NKEY_SEED: {{ .Values.source.natsNKeySeed | b64enc }}
{{- end }}
