name: Test & Build
on: push
jobs:
  test:
    name: Test
    runs-on: depot-ubuntu-22.04-8
    strategy:
      fail-fast: false
      matrix:
        # Supported Kubernetes versions are available here:
        # https://kubernetes.io/releases/
        kube_version:
          - v1.31.0
          - v1.30.4
          - v1.29.8
          - v1.28.13

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.x
          check-latest: true

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Vet
        run: go vet ./...

      - name: Test
        env:
          KUBE_VERSION: ${{ matrix.kube_version }}
        run: go test -v -race -timeout 3m ./...

  build:
    name: Build
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}
    needs:
      - test
    permissions:
      contents: read # required for checkout
      id-token: write # mint AWS credentials through OIDC
      packages: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: Dockerfile
            image_name: k8s-source

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/overmindtech/${{ matrix.image_name }}
            docker.cloudsmith.io/overmind/service/${{ matrix.image_name }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Cloudsmith Container Registry
        uses: docker/login-action@v3
        with:
          registry: docker.cloudsmith.io
          username: ${{ secrets.CLOUDSMITH_SERVICE_USER }}
          password: ${{ secrets.CLOUDSMITH_API_KEY }}

      - uses: depot/setup-action@v1

      - name: Build and push
        id: push
        uses: depot/build-push-action@v1
        with:
          project: xnsnw3m20t
          file: build/package/${{ matrix.dockerfile }}
          context: .
          sbom: true
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Prepare Deployment
        run: |
          echo "ghcr.io/overmindtech/${{ matrix.image_name }}@${{ steps.push.outputs.digest }}" | tee ${{ matrix.image_name }}.imageref

      - name: Upload Deployment File
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.image_name }}.imageref
          path: ${{ matrix.image_name }}.imageref

  publish-docs-data:
    name: Publish Docs Data
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}
    needs:
      - test
    permissions:
      contents: read # required for checkout
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Upload Docs Data
        uses: actions/upload-artifact@v4
        with:
          name: k8s-source-docs-data
          path: docs-data
